version: '3'
services:
#  mongodb:
#    image: mongo
#    container_name: mongo-test
#    ports:
#      - "27017:27017"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
  generator:
    image: simple-generator:2.0
    container_name: generator
    environment:
      HOST: mongo
      HOST_PORT: 27017
      DB: bikeService
    depends_on:
      - mongo